/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TutorService } from "../tutor.service";
import { TutorCreateInput } from "./TutorCreateInput";
import { Tutor } from "./Tutor";
import { TutorFindManyArgs } from "./TutorFindManyArgs";
import { TutorWhereUniqueInput } from "./TutorWhereUniqueInput";
import { TutorUpdateInput } from "./TutorUpdateInput";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";

export class TutorControllerBase {
  constructor(protected readonly service: TutorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tutor })
  async createTutor(@common.Body() data: TutorCreateInput): Promise<Tutor> {
    return await this.service.createTutor({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        biography: true,
        createdAt: true,
        id: true,
        rating: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Tutor] })
  @ApiNestedQuery(TutorFindManyArgs)
  async tutors(@common.Req() request: Request): Promise<Tutor[]> {
    const args = plainToClass(TutorFindManyArgs, request.query);
    return this.service.tutors({
      ...args,
      select: {
        biography: true,
        createdAt: true,
        id: true,
        rating: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tutor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tutor(
    @common.Param() params: TutorWhereUniqueInput
  ): Promise<Tutor | null> {
    const result = await this.service.tutor({
      where: params,
      select: {
        biography: true,
        createdAt: true,
        id: true,
        rating: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tutor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTutor(
    @common.Param() params: TutorWhereUniqueInput,
    @common.Body() data: TutorUpdateInput
  ): Promise<Tutor | null> {
    try {
      return await this.service.updateTutor({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          biography: true,
          createdAt: true,
          id: true,
          rating: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tutor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTutor(
    @common.Param() params: TutorWhereUniqueInput
  ): Promise<Tutor | null> {
    try {
      return await this.service.deleteTutor({
        where: params,
        select: {
          biography: true,
          createdAt: true,
          id: true,
          rating: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/courses")
  @ApiNestedQuery(CourseFindManyArgs)
  async findCourses(
    @common.Req() request: Request,
    @common.Param() params: TutorWhereUniqueInput
  ): Promise<Course[]> {
    const query = plainToClass(CourseFindManyArgs, request.query);
    const results = await this.service.findCourses(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        price: true,
        title: true,

        tutor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courses")
  async connectCourses(
    @common.Param() params: TutorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        connect: body,
      },
    };
    await this.service.updateTutor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courses")
  async updateCourses(
    @common.Param() params: TutorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        set: body,
      },
    };
    await this.service.updateTutor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courses")
  async disconnectCourses(
    @common.Param() params: TutorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        disconnect: body,
      },
    };
    await this.service.updateTutor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
